config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "listings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :listings
  get "my/listings", to: "listings#my_listings", as: :my_listings
  resources :bookings, except: %i[delete destroy]
  post "bookings/:id/cancel", to: "bookings#cancel", as: :cancel_booking
  post "bookings/:id/host_cancel", to: "bookings#host_cancel", as: :host_cancel_booking
  post "bookings/:id/host_accept", to: "bookings#host_accept", as: :host_accept_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :listing

  validates :start_date, :end_date, :guest_count, :payment_amount, :guest, :listing, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
  validates :guest_count, numericality: { only_integer: true }

  enum :status, { pending_host_confirmation: 0, accepted_by_host: 1, cancelled_by_host: 2, cancelled_by_guest: 3 }

  before_validation :calculate_payment

  def night_count
    (end_date - start_date).to_i
  end

  def calculate_payment
    self.payment_amount = (end_date - start_date).to_i * listing.price_per_night.to_i
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :bookings
  has_many_attached :images

  validates :title, presence: true, length: { minimum: 6, maximum: 100, too_long: "Your title should be 50 chars max.",
                                              too_short: "Your title should be 6 chars min." }
  validates :description, presence: true, length: { minimum: 20, maximum: 3500, too_long: "Your description should be 3500 chars max.",
                                                    too_short: "Your description should be 20 chars min." }
  validates :country, :images, presence: true
  validates :address, presence: true, uniqueness: true
  validates :bedroom_count, :bathroom_count, :bed_count, :guest_count, presence: true, numericality: { only_integer: true }
  validates :price_per_night, :service_fee, :cleaning_fee, presence: true, numericality: { greater_than: 0, less_than: 10_000 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/listing_review.rb
class Listingreview < ApplicationRecord
  belongs_to :booking
end

app/models/listingreview.rb
class Listingreview < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, foreign_key: 'host_id', class_name: 'Listing'
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :cancel, :host_cancel, :host_accept]
  before_action :set_listing, only: [:new]
  skip_before_action :verify_authenticity_token, only: [:cancel, :host_cancel, :host_accept]

  def index
    @bookings = policy_scope(Booking)
    @upcoming_bookings = @bookings.select { |booking|
      (booking.accepted_by_host? || booking.pending_host_confirmation?) && booking.end_date > Date.today }
    @past_bookings = @bookings.select { |booking| booking.end_date < Date.today && booking.accepted_by_host? }
    @cancelled_bookings = @bookings.select { |booking| booking.cancelled_by_guest? || booking.cancelled_by_host? }
  end

  def show
    authorize @booking
    @markers = [
      {
        lat: @booking.listing.latitude,
        lng: @booking.listing.longitude,
        info_window: render_to_string(partial: "info_window", locals: { booking: @booking })
      }

    ]
  end

  # http://localhost:3000/bookings/new?start_date=2022-10-10&end_date=2022-10-18&guest_count=5&listing_id=40
  def new
    @booking = Booking.new(
      start_date: params[:start_date],
      end_date: params[:end_date],
      guest_count: params[:guest_count],
      listing: @listing
    )

    @guest_count = params[:guest_count]
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.guest = current_user
    @listing = @booking.listing

    if @booking.save
      redirect_to booking_path(@booking), notice: "You have submitted your booking request!."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
  end

  def cancel
    authorize @booking

    @booking.cancelled_by_guest!
    render json: { message: "Cancelled by guest successful" }, status: :ok
  end

  def host_cancel
    authorize @booking

    @booking.cancelled_by_host!
    render json: { message: "Cancelled by host successful" }, status: :ok
  end

  def host_accept
    authorize @booking

    @booking.accepted_by_host!
    render json: { message: "Accepted by host successful" }, status: :ok
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :additional_requests, :guest_count, :listing_id)
  end

  def calculate_total_nights_amount
    @booking.listing.price_per_night * @booking.night_count
  end

  def total_amount
    service_fee = @booking.listing.service_fee
    cleaning_fee = @booking.listing.cleaning_fee
    calculate_total_nights_amount + service_fee + cleaning_fee
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @listings = Listing.all
  end

  def my_listings
    authorize Listing

    @listings = current_user.listings.includes(:bookings)
    bookings = @listings.map{ |l| l.bookings }.flatten.sort_by{ |b| b.start_date}
    @pending_bookings = bookings.select { |b| b.pending_host_confirmation? }
    @upcoming_bookings = bookings.select { |b| b.accepted_by_host? && b.start_date > Date.today }
    @past_bookings = bookings.select { |b| b.accepted_by_host? && b.end_date < Date.today}
    @cancelled_bookings = bookings.select { |b| b.cancelled_by_host?}
  end

  def show
    authorize @listing
    @booking = Booking.new
    @marker = [
      {
        lat: @listing.latitude,
        lng: @listing.longitude
      }
    ]
  end

  def new
    @listing = Listing.new
    authorize @listing
  end

  def create
    @listing = Listing.new(listing_params)

    @listing.host = current_user
    authorize @listing
    if @listing.save
      redirect_to @listing, notice: "Listing was successfully created."
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    authorize @listing
  end

  def update
    authorize @listing
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing has been updated."
    else
      render :edit
    end
  end

  def destroy
    authorize @listing
    @listing.destroy
    redirect_to my_listings_path, status: :see_other, notice: "Listing was successfully destroyed."
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :address, :country, :price_per_night, :bedroom_count,
                                    :bathroom_count, :bed_count, :guest_count, :house_rules, :service_fee, :cleaning_fee, images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_info_window.html.erb
<h6 class="fw-bolder mt-3">$<%= booking.listing.price_per_night.to_i %></h6>

app/views/bookings/index.html.erb
<div class="container" style="min-height: 90vh">
  <h1 class="my-4">Trip</h1>
  <h3 class="my-4 py-2 <%= "d-none" if @upcoming_bookings.empty? %>">Upcoming Trips</h3>
  <%= render "card", bookings: @upcoming_bookings %>

  <h3 class="my-4 py-2 <%= "d-none" if @past_bookings.empty? %>">Where you've been</h3>
  <%= render "card", bookings: @past_bookings %>

  <h3 class="my-4 py-2 <%= "d-none" if @cancelled_bookings.empty? %>">Cancelled</h3>
  <%= render "card", bookings: @cancelled_bookings %>
</div>

app/views/bookings/new.html.erb
<div class="row mx-5 my-3">
  <div class="col-lg-6 col-md-6 col-sm-12 px-5">
    <div class="">
      <div class="d-flex">
        <div class="m-2 back_link">
          <%= link_to listing_path(@listing), class: "link" do %>
            <i class="fa-solid fa-chevron-left"></i>
          <% end %>
        </div>
        <h1><strong>Request to book</strong></h1>
      </div>
      <div class="d-xs-block d-sm-block d-md-none d-lg-none d-xl-none">
        <%= render "summary_card" %>
      </div>
      <h4 class="my-4">Your trip</h4>
      <h6 class="my-3"><strong>Dates</strong></h6>
      <div class="d-flex justify-content-between">
        <p><%= @booking.start_date.strftime("%d %h %Y") %> - <%= @booking.end_date.strftime("%d %h %Y") %></p>
        <div>
          <button type="button" class="hollow-btn flex-grow-3 bg-white px-3 py-1" data-bs-toggle="modal" data-bs-target="#datepicker">
            Edit
          </button>

          <%= render "datepicker_modal" %>
        </div>
      </div>
      <h6 class="my-3"><strong>Guests</strong></h6>
      <div class="d-flex justify-content-between">
        <p><%= @guest_count %>
          <% if @booking.guest_count == 1 %>
            guest
          <% else %>
            guests
          <% end %>
        </p>
        <div>
          <button type="button" class="hollow-btn flex-grow-3 bg-white px-3 py-1" data-bs-toggle="modal" data-bs-target="#guest">
            Edit
          </button>

          <%= render "guest_modal"  %>
        </div>
      </div>
      <hr>
      <h4 class="my-4">Additional information for your trip</h4>
      <h6>Message the host</h6>
      <p class="small">Let the host know why you're travelling and when you'll check in</p>
    </div>
    <div class="my-3 d-flex align-items-center my-4">
      <div>
        <%= image_tag("logo.png", class: "avatar-large") %>
      </div>

      <div class="flex-grow-1 mx-2">
        <h5 class="my-0"><%= @booking.listing.host.first_name %></h5>
        <p class="my-0"><%=  @booking.listing.country%></p>
      </div>
    </div>

    <%= simple_form_for (@booking) do |f| %>
      <%= f.input :start_date, as: :hidden %>
      <%= f.input :end_date, as: :hidden %>
      <%= f.input :guest_count, as: :hidden %>
      <%= f.input :additional_requests, placeholder: "Your additional requests", input_html: { rows: "3" },  label: false %>

      <%= f.input :listing_id, :input_html => { value: @booking.listing.id }, as: :hidden %>
      <%= f.submit 'Request to book', class: "btn submit-btn" %>
    <% end %>
  </div>
  <div class='col-lg-6 col-md-6 col-sm-12 p-3 d-flex justify-content-center d-none d-md-block'>
    <%= render "summary_card" %>
  </div>
</div>

app/views/listings/_guest.html.erb
<select class="form-select" id="inlineFormCustomSelectPref">
  <% 15.times do |i| %>
    <option <%= "selected" if i ==0 %> value="<%= i + 1 %>"><%= i + 1 %></option>
  <% end %>
</select>

app/views/listings/edit.html.erb
<div class="container mt-4 w-800px">
  <div class="row">
    <div class="d-flex justify-content-between">
      <h1 class="mb-3">Edit your listing!</h1>
      <div class="p-0 mt-3">
        <%= link_to "Back to listings", my_listings_path , class: "hollow-btn" %>
      </div>
    </div>
    <%= render "form", listing: @listing %>
    <br>
  </div>
</div>

app/views/listings/index.html.erb
<br>

<div class="container">
  <div style="height: 2em;">
    <a class="btn btn-flat" href="#">Islands</a>
    <a class="btn btn-flat" href="#">Cities</a>
    <a class="btn btn-flat" href="#">Tropical</a>
    <a class="btn btn-flat" href="#">Luxury</a>
    <a class="btn btn-flat" href="#">Castles</a>
  </div>

  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 my-4">
        <div class="card border-0">
          <%= link_to listing_path(listing), class: "link" do %>
            <div>
              <% unless listing.images.empty? %>
                <% i = (0..(listing.images.size - 1)).to_a.sample %>
                <%= cl_image_tag listing.images[i].key, height: "auto", width: "300px", class:"card-img-top img-box" %>
              <% end %>
            </div>
          <% end %>
          <div class="card-body">
            <div style="height: 3em">
              <h6 class="card-title fw-bold mb-3"><%= listing.title %></h6>
            </div>
            <div class=" justify-content-start">
              <p class="small"><strong>$<%= listing.price_per_night.to_i%></strong> SGD night</p>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/listings/my_listings.html.erb
<div class="container">
  <div data-controller="my_listings">
    <div class="d-flex justify-content-between">
      <h1 class="my-3">Your listings' bookings</h1>
      <div class="py-4">
        <%= link_to "Create a new listing", new_listing_path, class: "hollow-btn" %>
      </div>
    </div>
    <div class="<%= "d-none" if @pending_bookings.empty? %>">
      <h5 class="mb-3">Pending confirmation</h5>
      <table class="table mb-5">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Listing Name</th>
            <th scope="col">Check-in</th>
            <th scope="col">Checkout</th>
            <th scope="col">Guest Name</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @pending_bookings.each_with_index do |booking, i|  %>
            <tr>
              <th scope="row"><%= i + 1 %></th>
              <td><%= booking.listing.title %></td>
              <td><%= booking.start_date.strftime("%d %h %Y") %></td>
              <td><%= booking.end_date.strftime("%d %h %Y") %></td>
              <td><%= booking.guest.first_name %></td>
              <td scope="col" class="d-flex">
                <button data-action="click->my_listings#updateBooking" href="<%= host_accept_booking_path(booking) %>" onclick="return confirm('Are you sure?')" class="color-txt">Accept</button>
                <button data-action="click->my_listings#updateBooking" href="<%= host_cancel_booking_path(booking) %>" onclick="return confirm('Are you sure?')" class="color-txt">Decline</button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="<%= "d-none" if @upcoming_bookings.empty? %>">
      <h5 class="mb-3">Upcoming bookings</h5>
      <%= render "booking_table", bookings: @upcoming_bookings %>
    </div>

    <div class="<%= "d-none" if @past_bookings.empty? %>">
      <h5 class="mb-3">Past bookings</h5>
      <%= render "booking_table", bookings: @past_bookings %>
    </div>

    <div class="<%= "d-none" if @cancelled_bookings.empty? %>">
      <h5 class="mb-3">Declined bookings</h5>
      <%= render "booking_table", bookings: @cancelled_bookings %>
    </div>
  </div>

  <div>
    <h1>Your listings</h1>
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="card mx-2 my-3 col-lg-4 col-md-6 col-sm-12 border-0" style="width: 18rem;">
          <%= link_to listing_path(listing), class: "link" do %>
            <% unless listing.images.empty? %>
              <% i = (0..(listing.images.size - 1)).to_a.sample %>
              <%= cl_image_tag listing.images[i].key, height: "auto", width: "300px", class:"card-img-top img-box" %>
            <% end %>
          <% end %>
          <div class="card-body">
            <div style="height: 4em">
              <h6 class="card-title fw-bold mb-3"><%= listing.title %></h6>
            </div>
            <div class="d-flex justify-content-start">
              <%= link_to "Edit", edit_listing_path(listing), class: "hollow-btn py-0 px-2" %>
              <% if listing.bookings.empty? %>
                <%= link_to "Delete", listing_path(listing), class: "hollow-btn py-0 px-2 mx-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="my-4">
    <div class="d-flex justify-content-between mx-2">
      <h3><%= @listing.title %></h3>
      <% if policy(@listing).edit? %>
        <div class="">
          <%= link_to "Edit this listing", edit_listing_path(@listing), class: "hollow-btn" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <p class="mx-2">
        <span class="<%= "d-none" if @listing.bookings.empty? %>">
          <i class="fa-solid fa-star"></i>
          4.97 · 82 reviews ·
        </span>
        <%= @listing.country %>
      </p>
    </div>
  </div>

  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <% @listing.images.each_with_index do |photo, i| %>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= i %>" class="<%= "active" if i == 0 %>" aria-current="<%= "true" if i == 0 %>" aria-label="Slide <%= i + 1 %>"></button>
      <% end %>
    </div>
    <div class="carousel-inner">
      <% @listing.images.each_with_index do |image, i| %>
        <div class="carousel-item <%= "active" if i == 0 %>">
          <%= cl_image_tag image.key, height: "auto", width: "100%", class: "d-block img-box-large" %>
        </div>
      <% end %>

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row mt-5">
    <div class="col-lg-7 col-md-8 col-sm-12 mt-3 pe-5" style= "width: 57%">
      <div class="my-3 d-flex align-items-center">
        <div class="ml-custom flex-grow-1 ms-2">
          <h5 class="my-0"><strong>Entire unit hosted by <%= @listing.host.first_name %></strong></h5>
          <p>
            <%= @listing.guest_count %> guests ·
            <%= @listing.bedroom_count %> bedrooms ·
            <%= @listing.bed_count%> bed ·
            <%= @listing.bathroom_count%> bathrooms
          </p>
        </div>
        <div>
          <%= image_tag("logo.png", class: "avatar-large", style: "margin-right: 24px") %>
        </div>
      </div>
      <hr class="ms-2">

      <div class="my-3 p-2">
        <div>
          <h5><strong>Description</strong></h5>
        </div>
        <p><%= @listing.description %></p>
        <hr>
        <div>
          <h5><strong>What this place offers</strong></h5>
        </div>
        <div class="d-flex flex-row w-100">
          <div class="d-flex flex-column my-3 w-50">
            <p><i class="fa-solid fa-kitchen-set listing-icon"></i>Kitchen</p>
            <p><i class="fa-solid fa-car listing-icon"></i>Free parking on premises</p>
            <p><i class="fa-solid fa-bath listing-icon"></i>Bath</p>
            <p><i class="fa-regular fa-seedling listing-icon"></i>Garden</p>
            <p><i class="fa-regular fa-tv listing-icon"></i>TV</p>
            <p class="listing-icon"> Mini-Fridge</p>
            <p><i class="fa-regular fa-kit-medical listing-icon"></i>First-Aid Kit</p>
            <p><i class="fa-regular fa-seedling listing-icon"></i>Cot</p>
          </div>
          <div class="d-flex flex-column my-3 w-50">
            <p><i class="fa-solid fa-wifi listing-icon"></i>WiFi</p>
            <p><i class="fa-solid fa-person-swimming listing-icon"></i>Private Pool</p>
            <p><i class="fa-duotone fa-pump-soap listing-icon"></i>Shampoo</p>
            <p><i class="fa-solid fa-snowflake listing-icon"></i>Air conditioning</p>
            <p><i class="fa-regular fa-tv listing-icon"></i>Hangers</p>
            <p><i class="fa-regular fa-mug-hot listing-icon"></i>Coffee</p>
            <p><i class="fa-regular fa-fire-extinguisher listing-icon"></i>Fire Extinguisher</p>
            <p><i class="fa-regular fa-seedling listing-icon"></i>Hot Water</p>
          </div>
        </div>
        <div class="my-4">
        <button type="button" class="listing-button p-2">Show all 20 amenities</button>
        </div>
        <hr>
      </div>
    </div>

    <div class="col-lg-5 col-md-4 col-sm-12 summary-card p-4 my-4" data-controller="listing">
      <div class="">
        <div class="d-flex flex-row">
          <h5 class="fw-bold">$<%= @listing.price_per_night.to_i %></h5>
          <p class="">/night</p>
        </div>

        <div class="d-flex">
          <i class="fa-solid fa-star"<%= "hidden" if @listing.bookings.empty? %>></i>
          <p class="mx-1"<%= "hidden" if @listing.bookings.empty? %>><strong>4.63</strong> (82 reviews)</p>
        </div>

        <form>
          <div class="row mb-4">
            <div class="col">
              <label for="formGroupExampleInput">Checkin</label>
              <input id="startDate" class="form-control" data-listing-target="startDate" type="date" value="<%= Date.today.strftime("%Y-%m-%d") %>" data-action="change->listing#startDateChange" min="<%= Date.today %>"/>
            </div>

            <div class="col">
              <label for="formGroupExampleInput">Checkout</label>
              <input id="endDate" class="form-control" data-listing-target="endDate" type="date" value="<%= (Date.today + 1).strftime("%Y-%m-%d") %>" data-action="change->listing#endDateChange" min="<%= Date.today + 1.day %>" />
            </div>
          </div>

          <div class="mb-4">
            <label for="formGroupExampleInput">Guests</label>
            <br>
            <select class="form-select" id="inlineFormCustomSelectPref" data-listing-target="guestCount">
              <option selected>1</option>
              <% (@listing.guest_count + 1).times do |i| %>
                <% next if i < 2 %>
                <option value="<%= i %>"><%= i %></option>
              <% end %>
            </select>
          </div>
          <h6 class="my-4 fw-custom">Payment amount</h6>
          <div class="d-flex justify-content-between">
            <p>$<%= @listing.price_per_night.to_i %> x
              <span data-listing-target="nightCount">
                1
              </span>
              night(s)
            </p>
            <p>$<span data-listing-target="subTotal"><%= total_amount = @listing.price_per_night.to_i %></span>
            </p>
          </div>

          <div class="d-flex justify-content-between">
          <p>Cleaning Fee</p>
          <p>$<%= @listing.cleaning_fee %></p>
          </div>

          <div class="d-flex justify-content-between">
            <p>Service Fee</p>
            <p>$<%= @listing.service_fee %></p>
          </div>

          <hr>

          <div class="d-flex justify-content-between mb-3">
            <p class="fw-custom">Total</p>
            <p>$
              <span data-listing-target="totalAmount">
                <%= @listing.price_per_night.to_i %>
              </span>
            </p>
          </div>
          <button type="submit" class="btn submit-btn p-1" href="<%= new_booking_path %>" data-action="click->listing#reserveBooking" <%= "disabled" if @listing.host == current_user %>>Reserve</button>

        </form>
      </div>
    </div>
  </div>

  <%# <h5><strong><%= @listing.title %>
  <%# hosted by <%= @listing.host.first_name %>
  <%# </strong></h5> %>


  <%# <% if policy(@listing).edit? %>
    <%# <%= link_to "Edit", edit_listing_path(@listing), class: "listing-link"%>
  <%# <% end %>

  <%# <%= link_to "Back", listings_path, class: "listing-link" %>

  <%# <% if policy(@listing).destroy? %>
    <%# <%= link_to "Delete", listing_path(@listing), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "listing-link" %>
  <%# <% end %>

  <div>
    <h5><strong>Where you'll be</strong></h5>
    <div class="listing-map mb-5"
      data-controller="map"
      data-map-markers-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

  <script>
    const pricePerNight = <%= @listing.price_per_night %>
    const cleaningFee = <%= @listing.cleaning_fee %>
    const serviceFee = <%= @listing.service_fee %>
    const listingId = <%= @listing.id %>
  </script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to listings_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn.iconscout.com/icon/free/png-256/social-258-116292.png", height: "35px", width: "auto" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div style="width: 65vw;">
    <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
    <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
      </button>
    </div>
    </form>
  </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create listing", new_listing_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Trips", bookings_path, class: "dropdown-item" %>
              <%= link_to "My Listings", my_listings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>